export const COUNTERS_INCREMENT = 'COUNTERS_INCREMENT';
export const COUNTERS_DECREMENT = 'COUNTERS_DECREMENT';
export const COUNTERS_RESET = 'COUNTERS_RESET';
export const COUNTERS_CHANGE_DEFAULT = 'COUNTERS_CHANGE_DEFAULT';